"""AmrAdapter：仅导航/充电/遥测/急停。不含电梯方法（DS-001）。"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable

from app.domain.dto import CommandHandle, Pose, RobotStatus

TelemetryCallback = Callable[[RobotStatus], None]


@runtime_checkable
class AmrAdapter(Protocol):
    robot_id: str

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def health(self) -> dict[str, Any]: ...
    async def get_status(self) -> RobotStatus: ...
    async def navigate_to(
        self,
        target: Pose | str,
        options: dict[str, Any] | None = None,
    ) -> CommandHandle: ...
    async def cancel(self, command_id: str | None = None) -> None: ...
    async def dock_charge(self) -> CommandHandle: ...
    def subscribe_telemetry(self, callback: TelemetryCallback) -> None: ...
    def unsubscribe(self) -> None: ...
