"""独立 ElevatorAdapter。调度编排调用 Call/Enter/Exit，不挂在 AmrAdapter。"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from app.domain.dto import CommandHandle, ElevatorStatus


@runtime_checkable
class ElevatorAdapter(Protocol):
    elevator_id: str

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def health(self) -> dict[str, Any]: ...
    async def get_status(self) -> ElevatorStatus: ...
    async def call_elevator(
        self, floor: int, options: dict[str, Any] | None = None
    ) -> CommandHandle: ...
    async def enter_elevator(self, options: dict[str, Any] | None = None) -> CommandHandle: ...
    async def exit_elevator(self, options: dict[str, Any] | None = None) -> CommandHandle: ...
