from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from app.domain.dto import TempHumidityReading


@runtime_checkable
class ClimateAdapter(Protocol):
    instrument_id: str

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def health(self) -> dict[str, Any]: ...
    async def read_temp_humidity(self) -> TempHumidityReading: ...
