from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from app.domain.dto import ChannelReading


@runtime_checkable
class ParticleAdapter(Protocol):
    instrument_id: str

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def health(self) -> dict[str, Any]: ...
    async def start_sample(self, params: dict[str, Any] | None = None) -> None: ...
    async def stop_sample(self) -> None: ...
    async def read_channels(self) -> list[ChannelReading]: ...
