"""对内设备适配器接口。业务编排只依赖这些方法，不出现厂商帧。"""

from __future__ import annotations

from typing import Protocol

from app.domain.dto import (
    AirSpeedReading,
    ChannelReading,
    CommandHandle,
    DeviceHealth,
    ElevatorStatus,
    Pose,
    RobotStatus,
    TempHumidityReading,
)


class AmrAdapter(Protocol):
    device_id: str
    adapter_type: str

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def health(self) -> DeviceHealth: ...
    def get_status(self) -> RobotStatus: ...
    def navigate_to(
        self,
        point_id: str | None = None,
        pose: Pose | None = None,
        options: dict | None = None,
    ) -> CommandHandle: ...
    def cancel(self, command_id: str | None = None) -> None: ...
    def dock_charge(self) -> CommandHandle: ...
    def subscribe_telemetry(self, callback) -> None: ...
    def unsubscribe(self, callback) -> None: ...


class ElevatorAdapter(Protocol):
    device_id: str
    adapter_type: str

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def health(self) -> DeviceHealth: ...
    def get_status(self) -> ElevatorStatus: ...
    def call_elevator(self, floor: int, options: dict | None = None) -> CommandHandle: ...
    def enter_elevator(self, options: dict | None = None) -> CommandHandle: ...
    def exit_elevator(self, options: dict | None = None) -> CommandHandle: ...


class ParticleAdapter(Protocol):
    device_id: str
    adapter_type: str
    access_mode: str

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def health(self) -> DeviceHealth: ...
    def start_sample(self, params: dict | None = None) -> CommandHandle: ...
    def stop_sample(self) -> CommandHandle: ...
    def read_channels(self) -> list[ChannelReading]: ...


class ClimateAdapter(Protocol):
    device_id: str
    adapter_type: str
    access_mode: str

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def health(self) -> DeviceHealth: ...
    def read_temp_humidity(self) -> TempHumidityReading: ...


class AirflowAdapter(Protocol):
    device_id: str
    adapter_type: str
    access_mode: str

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def health(self) -> DeviceHealth: ...
    def read_air_speed(self) -> AirSpeedReading: ...
