"""适配器 Protocol（DS §4.1）。业务只依赖本模块，不依赖厂商 SDK。"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from app.domain.models import (
    AirSpeedReading,
    ChannelReading,
    CommandHandle,
    ElevatorStatus,
    Pose,
    RobotStatus,
    TempHumidityReading,
)

TelemetryCallback = Callable[[RobotStatus], None]


class Lifecycle(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def health(self) -> dict[str, Any]: ...


class AmrAdapter(Protocol):
    """仅导航/充电/遥测/急停；不含电梯方法。"""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def health(self) -> dict[str, Any]: ...
    def get_status(self) -> RobotStatus: ...
    def navigate_to(self, target: Pose | str, options: dict[str, Any] | None = None) -> CommandHandle: ...
    def cancel(self, command_id: str | None = None) -> None: ...
    def dock_charge(self) -> CommandHandle: ...
    def subscribe_telemetry(self, callback: TelemetryCallback) -> None: ...
    def unsubscribe(self) -> None: ...
    def inject(self, **kwargs: Any) -> None: ...


class ElevatorAdapter(Protocol):
    """独立电梯适配器；调度编排调用 Call/Enter/Exit。"""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def health(self) -> dict[str, Any]: ...
    def get_status(self) -> ElevatorStatus: ...
    def call_elevator(self, floor: int, options: dict[str, Any] | None = None) -> CommandHandle: ...
    def enter_elevator(self, options: dict[str, Any] | None = None) -> CommandHandle: ...
    def exit_elevator(self, options: dict[str, Any] | None = None) -> CommandHandle: ...
    def inject(self, **kwargs: Any) -> None: ...


class ParticleAdapter(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def health(self) -> dict[str, Any]: ...
    def start_sample(self, params: dict[str, Any] | None = None) -> CommandHandle: ...
    def stop_sample(self) -> None: ...
    def read_channels(self) -> list[ChannelReading]: ...


class ClimateAdapter(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def health(self) -> dict[str, Any]: ...
    def read_temp_humidity(self) -> TempHumidityReading: ...


class AirflowAdapter(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def health(self) -> dict[str, Any]: ...
    def read_air_speed(self) -> AirSpeedReading: ...
